version: '3.3'
services:
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  # api:
  #   build: ./be
  # fe:
  #   buold: ./fe
  db:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=nude1234!!
      - MYSQL_DATABASE=nude
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - nude_mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  nude_mysql_db: {}